[package]
name = "bevy-drag-sprite"
version = "0.1.0"
authors = ["Manfred Kroehnert <mkroehnert@users.sourceforge.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
